apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-logs-dynamic-pvc

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName:
    app-logs-sc

  resources:
    requests:
      storage: 1Gi