apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prom-daemonset
  namespace: monitoring
  labels: 
    app: prom-daemonset
spec:
  selector:
    matchLabels:
      app: prom-daemonset
  template:
    metadata:
      labels:
        app: prom-daemonset
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
        operator: "Exists"
      containers:
      - name: prom-daemonset
        image: quay.io/prometheus/node-exporter:latest
        arguments:
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
        - --path.rootfs=/host/root
        ports:
        - containerPort: 9100
          name: metrics
          protocol: TCP
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: root  
          mountPath: /host/root
          readOnly: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: root
        hostPath:
          path: / 